FORMAT: 1A

# Olympics API
Olympics API  is ...

# Group Olympics
Olympics related resources of the **Olympics API**

## Years Collection [/olympics/years]
### List all Years [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
        
## Year [/olympics/years/{id}]
A single year with all it's details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Year desired. Has example value.

### Retrieve Year [GET]    
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
        
## Countries Collection [/olympics/countries]
### List all Countries [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
        
## Country [/olympics/countries/{id}]
A single country with all it's details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Country desired. Has example value.

### Retrieve Country [GET]    
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

## Events Collection [/olympics/events]
### List all Events [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
        
## Event [/olympics/events/{id}]
A single event with all it's details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Event desired. Has example value.

### Retrieve Event [GET]    
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
        
## Athletes Collection [/olympics/athletes]
### List all Athletes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
        
## Athlete [/olympics/athletes/{id}]
A single athlete with all it's details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Athlete desired. Has example value.

### Retrieve Athlete [GET]    
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
        
## Medals Collection [/olympics/medals]
### List all Medals [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
        
## Medal [/olympics/medals/{id}]
A single medal with all it's details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Medal desired. Has example value.

### Retrieve Medal [GET]    
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
        
## Medal By Rank [/olympics/medals/{rank}]
A medal rank with all it's details

+ Parameters
    + rank (required, string, `bronze`) ... String `id` of the Medal desired. Has example value.

### Retrieve Medal [GET]    
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }
